#!/bin/bash
if [[ $3 != "" ]]
	then
	echo -e"Too many arguments!\nSyntax: \e[1mrsum\e[0m <md5||sha|sha1|sha256|sha348|sha512> <path> <destination file>

find "$2" -type f -print0 | xargs -0 $1sum > "$3"

